[pytest]
# Папки, в которых Pytest будет искать тесты по умолчанию
testpaths = tests

# Регистрация кастомных маркеров (тэгов), чтобы не было предупреждений (warnings)
# Это аналог Labels/Tags в Jira или TestRail
markers =
    ui: UI тесты (Playwright)
    api: API тесты (Requests)
    unit: Unit тесты (проверка собственных утилит)
    smoke: Дымовые (критичные) тесты
    regression: Регрессионные тесты
    bdd: BDD тесты на Gherkin

# Базовые флаги, которые будут применяться при каждом запуске pytest:
# -v: подробный вывод
# -s: вывод принтов (print) в консоль
# --alluredir: куда сохранять результаты для красивого отчета
addopts = -v -s --alluredir=allure-results